name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print Hello
        run: echo "Hello Devops!"

      - name: Print data and time
        run: date

      - name: Show repo files
        run: ls -la


